### ISSUE TITLE
moment-timezone update

### ISSUE THREAD

**Issue by crsssl** [acreeger/meteor-moment-timezone#11]
Any plans to update this to the current version? moment-timezone is at v0.5.0 (2015-12-28)

**Comment by brucejo75** [comment]
+1, I would like to use moment.tz.guess(), available in v0.5.0.

**Comment by acreeger** [comment]
So, I haven't touched Meteor in a couple of years really, so I'm no longer maintaining this. If either of you want to take over, let me know and we can make it happen.

**Comment by crsssl** [comment]
I can do, Adam. Let me know how you want to handle this.

**Comment by acreeger** [comment]
For now, if you can open a PR with your changes, then I'll look into giving you the correct access so you can publish on atmosphere (assuming that's still the done thing).

**Comment by crsssl** [comment]
Looks like with Meteor 1.3, all this is moot. Thanks for the offer.
