### ISSUE TITLE
0.9.0

### ISSUE THREAD

**Issue by aldeed** [acreeger/meteor-moment-timezone#4]
Since I'm getting pressure to update my package for Meteor 0.9.0 and mine depends on yours, I'm forwarding the pressure to you. :) I see that you're working on publishing your moment pkg for 090, so it should be easy to update this package once you've done that.

**Comment by acreeger** [comment]
Literally on my to-do list for this evening...

**Comment by dkoo761** [comment]
+1. My app is broken after the upgrade to 0.9.0. This was the only package I was using that wasn't compatible with 0.9.0 so eagerly awaiting this update :)

**Comment by acreeger** [comment]
Done. Please check it out and let me know if you have any issues.

**Comment by dkoo761** [comment]
Looks good. Thanks!

**Comment by aldeed** [comment]
Thank you
